import { getAuthCookies } from "@/shared/lib/auth/cookies";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";
import QueryProvider from "./providers/QueryProvider";

const Pretendard = localFont({
  src: "../shared/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { accessToken, refreshToken } = await getAuthCookies();

  const hasToken = !!accessToken || !!refreshToken;
  return (
    <html lang="en" className={`${Pretendard.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <QueryProvider>
          {/* <AuthHydration> */}
          <AuthProvider>
            {children}
            <Script src="https://accounts.google.com/gsi/client" />
          </AuthProvider>
          {/* </AuthHydration> */}
        </QueryProvider>
      </body>
    </html>
  );
}
