name: Sync to Fork Repository

on:
  push:
    branches: [dev]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Team Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 내 개인 Fork 레포지토리로 코드를 강제 push(동기화)합니다.
      - name: Push to Fork Repo
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ROCKETDANTOKEN }}
          BRANCH: dev
          REPOSITORY: handy-o/undongda-gym
